<?php

define("DIRECTORIO_VISTA",env("DIRECTORIO_VIEWS"));
define("DIRECTORIO_RECURSOS",env("DIRECTORIO_RECURSOS"));
define("DIRECTORIO_LAYOUTS",env("DIRECTORIO_VIEWS_LAYOUT"));
define("URL_BASE",env("BASE_URL","http:://localhost/"));